export const EVENTS = [
    {
        id: 1,
        name: 'Предварительная защита проектов',
        format: 'Семинар',
        start_date: '12 марта',
        timeStart: '18:00',
        end_date: '14 марта',
        timeEnd: '18:00',
        city: 'Екатеринбург',
        visit_cost: 2100,
        photo_url: '',
    },
    {
        id: 2,
        name: 'Предварительная защита проектов',
        format: 'Семинар',
        start_date: '12 марта',
        timeStart: '18:00',
        end_date: '14 марта',
        timeEnd: '18:00',
        city: 'Екатеринбург',
        visit_cost: 2100,
        photo_url: '',
    },
    {
        id: 3,
        name: 'Предварительная защита проектов',
        format: 'Семинар',
        start_date: '12 марта',
        timeStart: '18:00',
        end_date: '14 марта',
        timeEnd: '18:00',
        city: 'Екатеринбург',
        visit_cost: 2100,
        photo_url: '',
    },
    {
        id: 4,
        name: 'Предварительная защита проектов',
        format: 'Семинар',
        start_date: '12 марта',
        timeStart: '18:00',
        end_date: '14 марта',
        timeEnd: '18:00',
        city: 'Екатеринбург',
        visit_cost: 2100,
        photo_url: '',
    },
    {
        id: 5,
        name: 'Предварительная защита проектов',
        format: 'Семинар',
        start_date: '12 марта',
        timeStart: '18:00',
        end_date: '14 марта',
        timeEnd: '18:00',
        city: 'Екатеринбург',
        visit_cost: 2100,
        photo_url: '',
    },
    {
        id: 6,
        name: 'Предварительная защита проектов',
        format: 'Семинар',
        start_date: '12 марта',
        timeStart: '18:00',
        end_date: '14 марта',
        timeEnd: '18:00',
        city: 'Екатеринбург',
        visit_cost: 2100,
        photo_url: '',
    },
];
