export const EVENTS = [
    {
        name: 'Предварительная защита проектов',
        type: 'Семинар',
        dateStart: '12 марта',
        timeStart: '18:00',
        dateEnd: '14 марта',
        timeEnd: '18:00',
        place: 'Екатеринбург',
        price: '2100₽',
    },
    {
        name: 'Предварительная защита проектов',
        type: 'Семинар',
        dateStart: '12 марта',
        timeStart: '18:00',
        dateEnd: '14 марта',
        timeEnd: '18:00',
        place: 'Екатеринбург',
        price: '2100₽',
    },
    {
        name: 'Предварительная защита проектов',
        type: 'Семинар',
        dateStart: '12 марта',
        timeStart: '18:00',
        dateEnd: '14 марта',
        timeEnd: '18:00',
        place: 'Екатеринбург',
        price: '2100₽',
    },
    {
        name: 'Предварительная защита проектов',
        type: 'Семинар',
        dateStart: '12 марта',
        timeStart: '18:00',
        dateEnd: '14 марта',
        timeEnd: '18:00',
        place: 'Екатеринбург',
        price: '2100₽',
    },
    {
        name: 'Предварительная защита проектов',
        type: 'Семинар',
        dateStart: '12 марта',
        timeStart: '18:00',
        dateEnd: '14 марта',
        timeEnd: '18:00',
        place: 'Екатеринбург',
        price: '2100₽',
    },
    {
        name: 'Предварительная защита проектов',
        type: 'Семинар',
        dateStart: '12 марта',
        timeStart: '18:00',
        dateEnd: '14 марта',
        timeEnd: '18:00',
        place: 'Екатеринбург',
        price: '2100₽',
    },
];
